name: VitalWikiClassifier
dependencies:
  - python=3.6
  - pip
  - numpy
  - pandas
  - spacy=2.0.12
  - nltk
  - keras-gpu
  - tensorflow-gpu
  - pytorch-gpu
  - cudatoolkit
  - matplotlib
  - scipy
  - scikit-learn
  - pip:
    - contractions
    - textsearch
    - daiquiri
    - hyperopt
    - scorch